"""Added ItemOwnership - User relation

Revision ID: 256308233b41
Revises: fafadd53204e
Create Date: 2022-10-13 14:38:10.778668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "256308233b41"
down_revision = "fafadd53204e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itemOwnerships",
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "itemOwnerships", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "itemOwnerships", type_="foreignkey")
    op.drop_column("itemOwnerships", "owner_id")
    # ### end Alembic commands ###
