"""Added User, Event and their relations

Revision ID: 2823eb3b2f6f
Revises: 29fef2b3718e
Create Date: 2022-10-11 22:49:37.941461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2823eb3b2f6f'
down_revision = '29fef2b3718e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('location', postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('eventParticipation',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('qust_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qust_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'qust_id')
    )
    op.create_index(op.f('ix_eventParticipation_qust_id'), 'eventParticipation', ['qust_id'], unique=False)
    op.create_index(op.f('ix_eventParticipation_user_id'), 'eventParticipation', ['user_id'], unique=False)
    op.create_table('itemOwnerships',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('obtained_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemOwnerships_id'), 'itemOwnerships', ['id'], unique=False)
    op.create_table('questParticipations',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('qust_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qust_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'qust_id')
    )
    op.create_index(op.f('ix_questParticipations_qust_id'), 'questParticipations', ['qust_id'], unique=False)
    op.create_index(op.f('ix_questParticipations_user_id'), 'questParticipations', ['user_id'], unique=False)
    op.add_column('items', sa.Column('icon', sa.String(), nullable=True))
    op.drop_column('items', 'collectible')
    op.drop_column('items', 'location')
    op.add_column('questItems', sa.Column('item_type', sa.Integer(), nullable=True))
    op.add_column('questItems', sa.Column('location', postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True))
    op.add_column('quests', sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'quests', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.drop_column('quests', 'event_id')
    op.drop_column('questItems', 'location')
    op.drop_column('questItems', 'item_type')
    op.add_column('items', sa.Column('location', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('collectible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('items', 'icon')
    op.drop_index(op.f('ix_questParticipations_user_id'), table_name='questParticipations')
    op.drop_index(op.f('ix_questParticipations_qust_id'), table_name='questParticipations')
    op.drop_table('questParticipations')
    op.drop_index(op.f('ix_itemOwnerships_id'), table_name='itemOwnerships')
    op.drop_table('itemOwnerships')
    op.drop_index(op.f('ix_eventParticipation_user_id'), table_name='eventParticipation')
    op.drop_index(op.f('ix_eventParticipation_qust_id'), table_name='eventParticipation')
    op.drop_table('eventParticipation')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
