"""Added Quest self reference

Revision ID: 29fef2b3718e
Revises: e1f061b21f93
Create Date: 2022-10-11 15:04:04.443371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29fef2b3718e'
down_revision = 'e1f061b21f93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questDependencies',
    sa.Column('quest_to_finish_before_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quest_to_finish_after_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_to_finish_after_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['quest_to_finish_before_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('quest_to_finish_before_id', 'quest_to_finish_after_id')
    )
    op.create_index(op.f('ix_questDependencies_quest_to_finish_after_id'), 'questDependencies', ['quest_to_finish_after_id'], unique=False)
    op.create_index(op.f('ix_questDependencies_quest_to_finish_before_id'), 'questDependencies', ['quest_to_finish_before_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questDependencies_quest_to_finish_before_id'), table_name='questDependencies')
    op.drop_index(op.f('ix_questDependencies_quest_to_finish_after_id'), table_name='questDependencies')
    op.drop_table('questDependencies')
    # ### end Alembic commands ###
