"""Add missing primary key to eventParticipations

Revision ID: 2a7adabcae52
Revises: 64cf80cfd867
Create Date: 2022-10-18 14:35:38.685234

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "2a7adabcae52"
down_revision = "64cf80cfd867"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "eventParticipations_pkey", "eventParticipation", ["user_id", "event_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "eventParticipations_pkey", "eventParticipation", type_="primary"
    )
    # ### end Alembic commands ###
