"""make username unique

Revision ID: 2edb3ecd6df9
Revises: 256308233b41
Create Date: 2022-10-18 11:24:02.279480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2edb3ecd6df9"
down_revision = "256308233b41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
