"""Fixed EventParticipation primary key name

Revision ID: 557fcd064859
Revises: bf1c9e8dd140
Create Date: 2022-10-11 22:52:33.892260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '557fcd064859'
down_revision = 'bf1c9e8dd140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventParticipation', sa.Column('quest_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_eventParticipation_qust_id', table_name='eventParticipation')
    op.create_index(op.f('ix_eventParticipation_quest_id'), 'eventParticipation', ['quest_id'], unique=False)
    op.drop_constraint('eventParticipation_qust_id_fkey', 'eventParticipation', type_='foreignkey')
    op.create_foreign_key(None, 'eventParticipation', 'events', ['quest_id'], ['id'])
    op.drop_column('eventParticipation', 'qust_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventParticipation', sa.Column('qust_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eventParticipation', type_='foreignkey')
    op.create_foreign_key('eventParticipation_qust_id_fkey', 'eventParticipation', 'events', ['qust_id'], ['id'])
    op.drop_index(op.f('ix_eventParticipation_quest_id'), table_name='eventParticipation')
    op.create_index('ix_eventParticipation_qust_id', 'eventParticipation', ['qust_id'], unique=False)
    op.drop_column('eventParticipation', 'quest_id')
    # ### end Alembic commands ###
