"""Add Voucher item type

Revision ID: 59f4ddda07bd
Revises: 6115668980db
Create Date: 2022-10-25 23:55:20.133525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59f4ddda07bd"
down_revision = "6115668980db"
branch_labels = None
depends_on = None

old_item_type_enum = sa.Enum("COLLECTIBLE", "KEY", "POI", name="itemtype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE itemtype ADD VALUE 'VOUCHER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE itemtype RENAME TO itemtype_old")
    old_item_type_enum.create(op.get_bind())
    op.execute(
        (
            "ALTER TABLE items ALTER COLUMN item_type TYPE itemtype USING \
            case WHEN item_type = 'VOUCHER' THEN 'COLLECTIBLE'::itemtype \
            ELSE item_type::text::itemtype END"
        )
    )
    op.execute("DROP TYPE itemtype_old")
    # ### end Alembic commands ###
