"""Rename quest_id to event_id in EventParticipation

Revision ID: 64cf80cfd867
Revises: 2edb3ecd6df9
Create Date: 2022-10-18 14:25:52.726280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64cf80cfd867"
down_revision = "2edb3ecd6df9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eventParticipation",
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.drop_index("ix_eventParticipation_quest_id", table_name="eventParticipation")
    op.create_index(
        op.f("ix_eventParticipation_event_id"),
        "eventParticipation",
        ["event_id"],
        unique=False,
    )
    op.drop_constraint(
        "eventParticipation_quest_id_fkey", "eventParticipation", type_="foreignkey"
    )
    op.create_foreign_key(None, "eventParticipation", "events", ["event_id"], ["id"])
    op.drop_column("eventParticipation", "quest_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eventParticipation",
        sa.Column("quest_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "eventParticipation", type_="foreignkey")
    op.create_foreign_key(
        "eventParticipation_quest_id_fkey",
        "eventParticipation",
        "events",
        ["quest_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_eventParticipation_event_id"), table_name="eventParticipation"
    )
    op.create_index(
        "ix_eventParticipation_quest_id",
        "eventParticipation",
        ["quest_id"],
        unique=False,
    )
    op.drop_column("eventParticipation", "event_id")
    # ### end Alembic commands ###
