"""Prepare item type and unclock method

Revision ID: 71cc79fd09c4
Revises: 557fcd064859
Create Date: 2022-10-13 12:22:19.457872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cc79fd09c4'
down_revision = '557fcd064859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questItems', 'item_type')
    op.drop_column('quests', 'unlock_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('unlock_method', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questItems', sa.Column('item_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
