"""Add Quest Completion unlock method

Revision ID: 97684545f321
Revises: 59f4ddda07bd
Create Date: 2022-10-26 00:09:05.291423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97684545f321"
down_revision = "59f4ddda07bd"
branch_labels = None
depends_on = None

old_unlock_method_enum = sa.Enum("QR_CODE", "LOCATION", name="unlockmethod")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE unlockmethod ADD VALUE 'QUEST_COMPLETION'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE unlockmethod RENAME TO unlockmethod_old")
    old_unlock_method_enum.create(op.get_bind())
    op.execute(
        (
            "ALTER TABLE \"questItems\" ALTER COLUMN unlock_method \
            TYPE unlockmethod USING \
            case WHEN unlock_method = 'QUEST_COMPLETION' THEN 'QR_CODE'::unlockmethod \
            ELSE unlock_method::text::unlockmethod END"
        )
    )
    op.execute(
        (
            "ALTER TABLE quests ALTER COLUMN unlock_method TYPE unlockmethod USING \
            case WHEN unlock_method = 'QUEST_COMPLETION' THEN 'QR_CODE'::unlockmethod \
            ELSE unlock_method::text::unlockmethod END"
        )
    )
    op.execute("DROP TYPE unlockmethod_old")
    # ### end Alembic commands ###
