"""Add missing primary key to questParticipations

Revision ID: a8a4fa746068
Revises: 2a7adabcae52
Create Date: 2022-10-18 14:43:36.644788

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8a4fa746068"
down_revision = "2a7adabcae52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "questParticipations_pkey", "questParticipations", ["user_id", "quest_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "questParticipations_pkey", "questParticipations", type_="primary"
    )
    # ### end Alembic commands ###
