"""Updated QuestStatus type

Revision ID: c0fc943b42f7
Revises: 109f30cf68bd
Create Date: 2022-10-18 11:04:41.928701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0fc943b42f7"
down_revision = "109f30cf68bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questParticipations",
        "status",
        existing_type=sa.INTEGER(),
        type_=sa.Enum("HIDDEN", "UNSTARTED", "ACTIVE", "FINISHED", name="queststatus"),
        postgresql_using="case WHEN status = 2 THEN 'UNSTARTED'::queststatus WHEN status = 3 THEN 'ACTIVE'::queststatus WHEN status = 4 THEN 'FINISHED'::queststatus ELSE 'HIDDEN'::queststatus END",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questParticipations",
        "status",
        existing_type=sa.Enum(
            "HIDDEN", "UNSTARTED", "ACTIVE", "FINISHED", name="queststatus"
        ),
        type_=sa.INTEGER(),
        postgresql_using="case \
                WHEN status = 'UNSTARTED' THEN 2::integer\
                WHEN status = 'ACTIVE' THEN 3::integer\
                WHEN status = 'FINISHED' THEN 4::integer\
                ELSE 1::integer END",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
