"""Add location to Item

Revision ID: d8cdf6fca749
Revises: a8a4fa746068
Create Date: 2022-10-19 10:55:37.038062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8cdf6fca749"
down_revision = "a8a4fa746068"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "location", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "location")
    # ### end Alembic commands ###
