"""Moved User location to QuestParticipation

Revision ID: fafadd53204e
Revises: 29268ba49dbb
Create Date: 2022-10-13 13:56:09.068173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fafadd53204e"
down_revision = "29268ba49dbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questParticipations",
        sa.Column(
            "location", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True
        ),
    )
    op.drop_column("users", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "location",
            postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("questParticipations", "location")
    # ### end Alembic commands ###
